"use client";

import { Trans, useTranslation } from "react-i18next";
import i18n from "../src/lib/i18n";

export default function HomePage() {
  const { t } = useTranslation();

  return (
    <main style={{ fontFamily: "sans-serif", padding: 24 }}>
      <h1>{t("home.title", "Home Title")}</h1>
      <p>{t("home.subtitle", { defaultValue: "Subtitle from i18next" })}</p>
      <p>{i18n.t("home.tagline", "Generated by Interceptor")}</p>
      <Trans i18nKey="home.cta">Get started now</Trans>
    </main>
  );
}
